### ISSUE TITLE
Implementing a Post Endpoint for Practice App: Ege Ekşi

### ISSUE THREAD

**Issue by egeek259** [bounswe/bounswe2023group5#246] opened 2023-05-11 09:49 UTC
### Description

In this task I will implement a "POST /yugiohcard" endpoint. This endpoint will basically do the following: based on the given card name, make a request to the Yugioh API and insert the response to the database to the designated schema/table. For detailed functionality the steps will be:

- [x] Get the given card name
- [x] Check whether the card name is valid
- [x] Make a request to Yugioh API endpoint based on the given card name
- [x] Get the response
- [x] Parse the response and insert the desired values to database such as card name, card id , card type etc.
- [x] Return a success message if everything is fine
- [x] Return an error message if an error occurs in previous steps

### 👮‍♀️ Reviewer

Deniz Ünal

### ⏰ Deadline

12.05.2023

**Comment by UnalDeniz** [comment] 2023-05-12 21:07
Your endpoint woks as intended, closing this issue

**Closed by UnalDeniz** 2023-05-12 21:07 UTC
Labels: Priority: High, Type: Feature, Status: In Progress
