### ISSUE TITLE
Generated unit test reports

### ISSUE THREAD

**Issue by alperen-bircak** [bounswe/bounswe2023group5#793] opened 2023-11-21 13:37 UTC
### Description

We need to provide generated unit test reports in milestone 2.

### 👮‍♀️ Reviewer

None

### ⏰ Deadline

30.11.2023

**Comment by halisbal** [comment] 2023-12-01 14:08
Since this issue is a duplicate of another issue, I am closing it.

**Closed by halisbal** 2023-12-01 14:08 UTC
Labels: Duplicate
