### ISSUE TITLE
Implementing the Game By Deal Endpoints

### ISSUE THREAD

**Issue by alperen-bircak** [bounswe/bounswe2023group5#201] opened 2023-05-08 09:35 UTC
### Description

I need to implement my endpoints for the practice app. The post endpoint will pull the data from external api and save it into the database, and the get endpoint will return this history specific to the user email.

### 👮‍♀️ Reviewer

Çisel Zümbül

### ⏰ Deadline

09.05.2023

**Comment by cisel-zumbul** [comment] 2023-05-20 12:16
It has been merged and tested, seems like it works as intended. Thank you for your good work. I've nothing to add, therefore, closing this issue.

**Closed by cisel-zumbul** 2023-05-20 12:16 UTC
Labels: Priority: High, Type: Feature, Status: In Progress
